packages:
  - packages/*
  - translate
  - components/**
  - "!**/test/**"
catalog:
  "@chromatic-com/storybook": ^3.2.2
  "@fontsource/jetbrains-mono": ^5.1.1
  "@hello-pangea/dnd": ^17.0.0
  "@mantine/carousel": ^7.14.3
  "@mantine/charts": ^7.14.3
  "@mantine/code-highlight": ^7.14.3
  "@mantine/core": ^7.14.3
  "@mantine/dates": ^7.14.3
  "@mantine/dropzone": ^7.14.3
  "@mantine/form": ^7.14.3
  "@mantine/hooks": ^7.14.3
  "@mantine/modals": ^7.14.3
  "@mantine/notifications": ^7.14.3
  "@mantine/nprogress": ^7.14.3
  "@mantine/spotlight": ^7.14.3
  "@mantine/tiptap": ^7.14.3
  "@storybook/addon-essentials": ^8.4.7
  "@storybook/addon-interactions": ^8.4.7
  "@storybook/addon-onboarding": ^8.4.7
  "@storybook/addon-styling-webpack": ^1.0.1
  "@storybook/blocks": ^8.4.7
  "@storybook/preview-api": ^8.4.7
  "@storybook/react": ^8.4.7
  "@storybook/react-vite": ^8.4.7
  "@storybook/test": ^8.4.7
  "@tabler/icons-react": ^3.24.0
  "@tanstack/react-query": ^5.62.3
  "@tanstack/react-query-devtools": ^5.62.3
  "@tiptap/extension-link": ^2.10.3
  "@tiptap/pm": ^2.10.3
  "@tiptap/react": ^2.10.3
  "@tiptap/starter-kit": ^2.10.3
  "@types/react-big-calendar": ^1.16.0
  "@vitejs/plugin-react": ^4.3.4
  "@xyflow/react": ^12.3.5
  autoprefixer: ^10.4.20
  axios: ^1.7.9
  clsx: ^2.1.1
  concurrently: ^9.1.0
  dayjs: ^1.11.13
  embla-carousel-react: ^7.1.0
  eslint-plugin-storybook: ^0.11.1
  i18next: ^24.0.5
  i18next-browser-languagedetector: ^8.0.0
  mantine-contextmenu: ^7.14.2
  mitt: ^3.0.1
  postcss: ^8.4.49
  postcss-preset-mantine: ^1.17.0
  postcss-simple-vars: ^7.0.1
  prettier: ^3.4.1
  prop-types: ^15.8.1
  react: ^18.3.1
  react-big-calendar: ^1.16.3
  react-devtools: ^6.0.1
  react-dom: ^18.3.1
  react-i18next: ^15.1.3
  react-router: ^7.0.2
  react-scan: ^0.0.35
  react-use-websocket: ^4.11.1
  recharts: ^2.14.1
  rollup-plugin-visualizer: ^5.12.0
  sass-embedded: ^1.82.0
  storybook: ^8.4.7
  storybook-dark-mode: ^4.0.2
  tailwindcss: ^3.4.16
  unplugin-turbo-console: ^1.10.6
  validator: ^13.12.0
  vite-plugin-compression2: ^1.3.3
  vite-plugin-dts: ^4.3.0
  vite-plugin-pwa: ^0.21.1
  vite-tsconfig-paths: ^5.1.4
  zustand: ^5.0.2
