# https://taskfile.dev

version: '3'

vars:
  APP_NAME: maxio
  DIST_DIR: dist
  VERSION: 0.0.1
  GIT_COMMIT:
    sh: git rev-parse --short HEAD

tasks:
  build:
    cmds:
      - GOOS={{OS}} GOARCH={{ARCH}} go build -trimpath -ldflags="-s -w" -o {{.DIST_DIR}}/{{.APP_NAME}}-{{.VERSION}}-{{OS}}-{{ARCH}} .
      - |
        if [ "{{OS}}" != "darwin" ]; then
          upx -9 {{.DIST_DIR}}/{{.APP_NAME}}-{{.VERSION}}-{{OS}}-{{ARCH}}
        else
          echo "Skipping upx on macOS"
        fi