services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: nexus
      POSTGRES_PASSWORD: nexus
      POSTGRES_DB: nexus

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: "nexus"
      MINIO_ROOT_PASSWORD: "nexus_minio_password"
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    #    volumes:
    #      - data:/data
    #      - config:/root/.minio
    command: server /data --console-address ":9001"