[package]
name = "tcp_entry"
version.workspace = true
edition.workspace = true

[dependencies]
entry = { path = "../entry" }
async-trait = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true, features = ["rt", "rt-multi-thread", "net", 'macros'] }